/*
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.permit.sdk.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * supported attribute primitives
 */
@JsonAdapter(AttributeType.Adapter.class)
public enum AttributeType {
  
  BOOL("bool"),
  
  NUMBER("number"),
  
  STRING("string"),
  
  TIME("time"),
  
  JSON("json");

  private String value;

  AttributeType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AttributeType fromValue(String value) {
    for (AttributeType b : AttributeType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AttributeType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AttributeType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AttributeType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AttributeType.fromValue(value);
    }
  }
}

