/*
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.permit.sdk.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.permit.sdk.openapi.JSON;

/**
 * InviteAttemptResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-13T15:32:07.306280+03:00[Asia/Jerusalem]")
public class InviteAttemptResult {
  public static final String SERIALIZED_NAME_INVITE_SUCCESSFUL = "invite_successful";
  @SerializedName(SERIALIZED_NAME_INVITE_SUCCESSFUL)
  private Boolean inviteSuccessful;

  public static final String SERIALIZED_NAME_INVITE_FAILED_REASON = "invite_failed_reason";
  @SerializedName(SERIALIZED_NAME_INVITE_FAILED_REASON)
  private String inviteFailedReason;

  public InviteAttemptResult() {
  }

  public InviteAttemptResult inviteSuccessful(Boolean inviteSuccessful) {
    
    this.inviteSuccessful = inviteSuccessful;
    return this;
  }

   /**
   * the invite code was accepted
   * @return inviteSuccessful
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the invite code was accepted")

  public Boolean getInviteSuccessful() {
    return inviteSuccessful;
  }


  public void setInviteSuccessful(Boolean inviteSuccessful) {
    this.inviteSuccessful = inviteSuccessful;
  }


  public InviteAttemptResult inviteFailedReason(String inviteFailedReason) {
    
    this.inviteFailedReason = inviteFailedReason;
    return this;
  }

   /**
   * if the invite failed, the reason it failed
   * @return inviteFailedReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "if the invite failed, the reason it failed")

  public String getInviteFailedReason() {
    return inviteFailedReason;
  }


  public void setInviteFailedReason(String inviteFailedReason) {
    this.inviteFailedReason = inviteFailedReason;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InviteAttemptResult inviteAttemptResult = (InviteAttemptResult) o;
    return Objects.equals(this.inviteSuccessful, inviteAttemptResult.inviteSuccessful) &&
        Objects.equals(this.inviteFailedReason, inviteAttemptResult.inviteFailedReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inviteSuccessful, inviteFailedReason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InviteAttemptResult {\n");
    sb.append("    inviteSuccessful: ").append(toIndentedString(inviteSuccessful)).append("\n");
    sb.append("    inviteFailedReason: ").append(toIndentedString(inviteFailedReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("invite_successful");
    openapiFields.add("invite_failed_reason");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InviteAttemptResult
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (InviteAttemptResult.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in InviteAttemptResult is not found in the empty JSON string", InviteAttemptResult.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!InviteAttemptResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InviteAttemptResult` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("invite_failed_reason") != null && !jsonObj.get("invite_failed_reason").isJsonNull()) && !jsonObj.get("invite_failed_reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `invite_failed_reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("invite_failed_reason").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InviteAttemptResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InviteAttemptResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InviteAttemptResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InviteAttemptResult.class));

       return (TypeAdapter<T>) new TypeAdapter<InviteAttemptResult>() {
           @Override
           public void write(JsonWriter out, InviteAttemptResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InviteAttemptResult read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InviteAttemptResult given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InviteAttemptResult
  * @throws IOException if the JSON string is invalid with respect to InviteAttemptResult
  */
  public static InviteAttemptResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InviteAttemptResult.class);
  }

 /**
  * Convert an instance of InviteAttemptResult to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

