/*
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.permit.sdk.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(OnboardingStep.Adapter.class)
public enum OnboardingStep {
  
  CREATE_ORGANIZATION("create_organization"),
  
  CREATE_PROJECT("create_project"),
  
  CREATE_RESOURCE("create_resource"),
  
  CREATE_ACTIONS("create_actions"),
  
  ASSIGN_PERMISSIONS("assign_permissions"),
  
  ASSIGN_USER_ROLES("assign_user_roles"),
  
  CONNECT_SDK("connect_sdk"),
  
  DONE("done");

  private String value;

  OnboardingStep(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OnboardingStep fromValue(String value) {
    for (OnboardingStep b : OnboardingStep.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OnboardingStep> {
    @Override
    public void write(final JsonWriter jsonWriter, final OnboardingStep enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OnboardingStep read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OnboardingStep.fromValue(value);
    }
  }
}

