/*
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.permit.sdk.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.permit.sdk.openapi.model.APIKeyInfo;
import io.permit.sdk.openapi.model.APIKeyViewerContext;
import io.permit.sdk.openapi.model.MemberInfo;
import io.permit.sdk.openapi.model.MemberViewerContext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import io.permit.sdk.openapi.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-13T15:32:07.306280+03:00[Asia/Jerusalem]")
public class Viewer extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(Viewer.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Viewer.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Viewer' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<APIKeyViewerContext> adapterAPIKeyViewerContext = gson.getDelegateAdapter(this, TypeToken.get(APIKeyViewerContext.class));
            final TypeAdapter<MemberViewerContext> adapterMemberViewerContext = gson.getDelegateAdapter(this, TypeToken.get(MemberViewerContext.class));

            return (TypeAdapter<T>) new TypeAdapter<Viewer>() {
                @Override
                public void write(JsonWriter out, Viewer value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `APIKeyViewerContext`
                    if (value.getActualInstance() instanceof APIKeyViewerContext) {
                        JsonObject obj = adapterAPIKeyViewerContext.toJsonTree((APIKeyViewerContext)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    // check if the actual instance is of the type `MemberViewerContext`
                    if (value.getActualInstance() instanceof MemberViewerContext) {
                        JsonObject obj = adapterMemberViewerContext.toJsonTree((MemberViewerContext)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                        return;
                    }

                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: APIKeyViewerContext, MemberViewerContext");
                }

                @Override
                public Viewer read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    // deserialize APIKeyViewerContext
                    try {
                        // validate the JSON object to see if any exception is thrown
                        APIKeyViewerContext.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'APIKeyViewerContext'");
                        Viewer ret = new Viewer();
                        ret.setActualInstance(adapterAPIKeyViewerContext.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'APIKeyViewerContext'", e);
                    }

                    // deserialize MemberViewerContext
                    try {
                        // validate the JSON object to see if any exception is thrown
                        MemberViewerContext.validateJsonObject(jsonObject);
                        log.log(Level.FINER, "Input data matches schema 'MemberViewerContext'");
                        Viewer ret = new Viewer();
                        ret.setActualInstance(adapterMemberViewerContext.fromJsonTree(jsonObject));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'MemberViewerContext'", e);
                    }


                    throw new IOException(String.format("Failed deserialization for Viewer: no class matched. JSON: %s", jsonObject.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public Viewer() {
        super("anyOf", Boolean.FALSE);
    }

    public Viewer(APIKeyViewerContext o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Viewer(MemberViewerContext o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("APIKeyViewerContext", new GenericType<APIKeyViewerContext>() {
        });
        schemas.put("MemberViewerContext", new GenericType<MemberViewerContext>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return Viewer.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * APIKeyViewerContext, MemberViewerContext
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof APIKeyViewerContext) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof MemberViewerContext) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be APIKeyViewerContext, MemberViewerContext");
    }

    /**
     * Get the actual instance, which can be the following:
     * APIKeyViewerContext, MemberViewerContext
     *
     * @return The actual instance (APIKeyViewerContext, MemberViewerContext)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `APIKeyViewerContext`. If the actual instance is not `APIKeyViewerContext`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `APIKeyViewerContext`
     * @throws ClassCastException if the instance is not `APIKeyViewerContext`
     */
    public APIKeyViewerContext getAPIKeyViewerContext() throws ClassCastException {
        return (APIKeyViewerContext)super.getActualInstance();
    }

    /**
     * Get the actual instance of `MemberViewerContext`. If the actual instance is not `MemberViewerContext`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `MemberViewerContext`
     * @throws ClassCastException if the instance is not `MemberViewerContext`
     */
    public MemberViewerContext getMemberViewerContext() throws ClassCastException {
        return (MemberViewerContext)super.getActualInstance();
    }


 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Viewer
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
    // validate anyOf schemas one by one
    int validCount = 0;
    // validate the json string with APIKeyViewerContext
    try {
      APIKeyViewerContext.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    // validate the json string with MemberViewerContext
    try {
      MemberViewerContext.validateJsonObject(jsonObj);
      return; // return earlier as at least one schema is valid with respect to the Json object
      //validCount++;
    } catch (Exception e) {
      // continue to the next one
    }
    if (validCount == 0) {
      throw new IOException(String.format("The JSON string is invalid for Viewer with anyOf schemas: APIKeyViewerContext, MemberViewerContext. JSON: %s", jsonObj.toString()));
    }
  }

 /**
  * Create an instance of Viewer given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Viewer
  * @throws IOException if the JSON string is invalid with respect to Viewer
  */
  public static Viewer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Viewer.class);
  }

 /**
  * Convert an instance of Viewer to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

