/*
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.permit.sdk.openapi.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * GroupAssignUser
 * <p>
 *
 *
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-26T18:29:37.439030+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.17.0")
public class GroupAssignUser {
    /**
     * Tenant
     * <p>
     * the tenant key or id that the user belongs to.
     * (Required)
     */
    @SerializedName("tenant")
    @Expose
    public String tenant;

    /**
     *

     * @param tenant
     */
    public GroupAssignUser(java.lang.String tenant) {
        super();
        this.tenant = tenant;
    }

    public GroupAssignUser withTenant(java.lang.String tenant) {
        this.tenant = tenant;
        return this;
    }
}

