/*
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.permit.sdk.openapi;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
                .registerTypeSelector(io.permit.sdk.openapi.model.Viewer.class, new TypeSelector<io.permit.sdk.openapi.model.Viewer>() {
                    @Override
                    public Class<? extends io.permit.sdk.openapi.model.Viewer> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("APIKeyViewerContext", io.permit.sdk.openapi.model.APIKeyViewerContext.class);
                        classByDiscriminatorValue.put("MemberViewerContext", io.permit.sdk.openapi.model.MemberViewerContext.class);
                        classByDiscriminatorValue.put("api_key", io.permit.sdk.openapi.model.APIKeyViewerContext.class);
                        classByDiscriminatorValue.put("member", io.permit.sdk.openapi.model.MemberViewerContext.class);
                        classByDiscriminatorValue.put("Viewer", io.permit.sdk.openapi.model.Viewer.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "type"));
                    }
          })
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.APIKeyInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.APIKeyRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.APIKeyScopeRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.APIKeyViewerContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ActionBlockEditable.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ActionBlockRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.AddRolePermissions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.AssignedRole.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.AttributeBlock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Attributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.DataSourceConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.DataSourceEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.DecisionLogGrantPermissions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.DecisionLogResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.DecisionLogResponseList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.DecisionLogResultResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.DevLogin.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.EnvironmentCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.EnvironmentRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.EnvironmentUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.FailedInvite.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.FullData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.HTTPValidationError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.IdentityRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.InviteAttemptResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.InviteCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.InviteRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.JSONPatchAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Labels.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.LocationInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.LoginResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.MemberInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.MemberViewerContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.MultiInviteResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.NewOrganization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.NewPDP.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.NewProject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.NewRemoteTenant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.NewRemoteUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.NewTenant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.NewUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OPADecisionLog.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OPALClient.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OrgMemberRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OrgMemberUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Organization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OrganizationCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OrganizationList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OrganizationRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.OrganizationUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PDP.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PDPConfigRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PDPContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PDPInfoRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PDPList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PaginatedResultOPADecisionLog.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PaginatedResultUserRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PDP.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PdpValues.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Permission.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PermitBackendSchemasSchemaInstructionsLanguageInstructions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PermitBackendSchemasSchemaPDPsRemoteConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PermitBackendV1CompatSchemasInstructionsLanguageInstructions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.PermitBackendV1CompatSchemasSdkRemoteConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Project.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ProjectCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ProjectList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ProjectRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ProjectUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RemoveRolePermissions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceActionCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceActionRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceActionUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceAttributeCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceAttributeRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceAttributeUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceReplace.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceRoleCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceRoleRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceRoleUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ResourceUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Role.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleAssignmentCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleAssignmentRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleAssignmentRemove.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleBlock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleDef.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.RoleUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.TeamMember.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.TeamMemberList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Tenant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.TenantCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.TenantList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.TenantRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.TenantUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UpdateOrganization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UpdatePDP.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UpdateProject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UpdateTeamMember.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UpdateTenant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UpdateUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.User.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserListWithRoles.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserRead.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserRole.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserRoleCreate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserRoleRemove.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserRoles.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserWithOptionalPatch.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserWithRoles.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.UserRoles.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ValidationError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.Viewer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ViewerContext.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.permit.sdk.openapi.model.ViewerGrant.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
