/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.permit.sdk;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PermitClientTest {
    @Test void someLibraryMethodReturnsTrue() {
        PermitClient classUnderTest = new PermitClient();
        assertTrue(classUnderTest.isTrue(), "someLibraryMethod should return 'true'");
    }
}
